### ISSUE TITLE
OBIS not in list of GBIF endorsing nodes

### ISSUE THREAD

**Issue by wardappeltans** [iobis/gbif-marine#13]
Registration of the Deep-Sea OBIS node failed. OBIS is not in the pick-list of endorsing nodes.

This was recommended under point 3 of [How to Publish your data to GBIF](https://github.com/iobis/gbif-marine/wiki/How-to-serve-your-datasets-from-your-OBIS-node-to-GBIF), which ensures OBIS nodes are listed under OBIS.

**Comment by Antonarctica** [comment]
Hi IS this resolved?
AntOBIS is endorsed by OBIS..
https://www.gbif.org/publisher/104e9c96-791b-4f14-978c-f581cb214912

So this could be a technical bug.

**Comment by wardappeltans** [comment]
GBIF has solved it in this way (see attached)

![screen shot 2018-04-12 at 11 01 46](https://user-images.githubusercontent.com/15197599/38667249-361f7be8-3e41-11e8-86f8-bf009ff445a8.png)
