### ISSUE TITLE
 IPT resource data licenses 

### ISSUE THREAD

**Issue by OBISCanada** [iobis/gbif-marine#6]
Could OBIS clarify how data licenses associated with an IPT resource are made visible to data users?

Is the basic procedure as follows? -->Data license harvested by OBIS from the front page (basic metadata) of the IPT EML. This license is copied into IMIS and into the iOBIS database. The license is added to use constraints in the OBIS metadata for each resource which is then made visible on the OBIS portal. A data user may view this license if they click on the little (i) button next to a resource name – this will pop open the metadata.

A data user may download a list of resources associated with search criteria – in the past there was a request to have the resource citation included in this file. Perhaps the data license should also be included?

There are DwC fields that may be populated for rightsHolder and license. Will OBIS promote the population of these fields?

**Comment by wardappeltans** [comment]
Dear Mary, we will document this on the training pages at https://github.com/iobis/training/wiki, but for the time being this resource can be used that explains the metadata fields in EML: http://library.oceanteacher.org/OTMediawiki/index.php/OBIS_metadata (note that this page will be offline soon).
